# Generated by Django 5.1.1 on 2025-03-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_created_at_teacher_created_at_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
