# Generated by Django 5.1.1 on 2025-03-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_student_username_alter_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
