# Generated by Django 5.1.1 on 2025-03-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclass',
            name='country',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='bookclass',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bookclass',
            name='full_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
