# Generated by Django 5.1.1 on 2025-03-26 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_bookclass_country_bookclass_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='total_lectures',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='classes_live',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='courses_ending_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='courses_joining_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='courses_ongoing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.courses'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses_progress',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
