# Generated by Django 5.1.1 on 2025-03-26 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_courses_user_courses_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses_ongoing',
        ),
        migrations.AddField(
            model_name='courses',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='courses_ongoing',
            field=models.ManyToManyField(null=True, to='myapp.courses'),
        ),
    ]
