# Generated by Django 5.1.1 on 2025-03-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_courses_user_remove_student_courses_ongoing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
