# Generated by Django 5.1.1 on 2025-04-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(max_length=29, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parents_phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
