# Generated by Django 5.1.1 on 2025-04-07 06:32

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeclass',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
