# Generated by Django 5.1.1 on 2025-04-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_gradeclass_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeclass',
            name='country',
        ),
    ]
