# Generated by Django 5.1.1 on 2025-04-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_enrollment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classes_live',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses_ending_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses_joining_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses_progress',
        ),
        migrations.AddField(
            model_name='student',
            name='wish_list',
            field=models.ManyToManyField(related_name='wish_list', to='myapp.courses'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses_ongoing',
            field=models.ManyToManyField(related_name='courses_ongoing', to='myapp.courses'),
        ),
    ]
