# Generated by Django 5.2 on 2025-04-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
