# Generated by Django 5.2 on 2025-04-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_resources_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('meet_link', models.URLField(blank=True)),
                ('recording_link', models.URLField(blank=True)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
