# Generated by Django 5.2 on 2025-04-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_meeting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='total_days',
            field=models.IntegerField(null=True),
        ),
    ]
