# Generated by Django 5.2 on 2025-04-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_remove_enrollment_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='days_between',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='repeat_count',
            field=models.IntegerField(default=1),
        ),
    ]
