# Generated by Django 5.2 on 2025-05-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_certificate_certificate_code_certificate_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
