# Generated by Django 5.2 on 2025-05-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_certificate_certificate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='grade',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
