# Generated by Django 5.2 on 2025-05-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_certificate_created_at_alter_certificate_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_code',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='grade',
        ),
    ]
