# Generated by Django 5.2 on 2025-05-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_remove_certificate_certificate_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='grade',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
