# Generated by Django 5.2 on 2025-05-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_certificate_certificate_code_certificate_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificate'),
        ),
    ]
