# Generated by Django 5.2 on 2025-06-10 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_teacher_first_name_teacher_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclass',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher'),
        ),
    ]
