# Generated by Django 5.2 on 2025-06-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_feedback_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='college',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
