# Generated by Django 5.2 on 2025-06-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_teacher_college_teacher_degree_teacher_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='video',
            field=models.FileField(null=True, upload_to='resources_video/'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='pdf_file/'),
        ),
    ]
