# Generated by Django 5.2 on 2025-06-10 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_resources_video_alter_resources_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher'),
        ),
    ]
