# Generated by Django 5.2 on 2025-06-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_resources_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclass',
            name='completed',
            field=models.BooleanField(default='False', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='completed',
            field=models.BooleanField(default='False', null=True),
        ),
    ]
