# Generated by Django 5.2 on 2025-06-13 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_meeting_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_title', models.CharField(blank=True, max_length=100, null=True)),
                ('badge_level', models.CharField(blank=True, max_length=100, null=True)),
                ('badge_points', models.TextField(blank=True, null=True)),
                ('badge_image', models.ImageField(upload_to='badge_image/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher')),
            ],
        ),
    ]
