# Generated by Django 5.2 on 2025-06-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='badge_image',
        ),
    ]
